### ISSUE TITLE
Support setting remotetapclient URL

### ISSUE THREAD

**Issue by devurandom** [jaronoff97/tails#15]
Currently the remotetapclient URL is hardcoded to `ws://localhost:12001` in https://github.com/jaronoff97/tails/blob/9d271659aee24507d10ddc26141a02fe52c81727/lib/tails/remotetapclient.ex#L9

I am operating my application in a Compose environment (local development) and would like for Tails to be able to connect to the OpenTelemetry Collector in a different container. A simple `TAILS_REMOTETAP_ENDPOINT` env var (with value e.g. `ws://collector:12001`) would be sufficient.

**Comment by jaronoff97** [comment]
yep! I was thinking I may even make this configurable from the UI too. Would that be preferable over an environment variable?

**Comment by devurandom** [comment]
> Would that be preferable over an environment variable?

No. I need to configure Tails from the Compose file, so it will behave the same whenever I recreate the containers. The easiest way for me to do that is adding an env var to the Compose file.

**Comment by jaronoff97** [comment]
awesome! can do.

**Comment by jaronoff97** [comment]
you can now set `REMOTE_TAP_ENDPOINT` :D

**Comment by devurandom** [comment]
Confirmed: Tails works now! Thanks!

I am using a collector config similar to this:
```yaml
extensions:
  opamp:
    server:
      ws:
        # https://opentelemetry.io/docs/collector/configuration/#environment-variables
        endpoint: "${env:TAILS_OPAMP_ENDPOINT}"
        tls:
          insecure: true
processors:
  batch:
    send_batch_size: 1024
    timeout: 10s
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  remotetap:
    endpoint: 0.0.0.0:12001
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  debug: # Collector complains if an exporter has no config at all
  otlp/jaeger:
    # https://opentelemetry.io/docs/collector/configuration/#environment-variables
    endpoint: "${env:JAEGER_OTLP_ENDPOINT}"
    tls:
      insecure: true
service:
  extensions:
    - opamp
  telemetry:
    logs:
      level: "warn"
  pipelines:
    metrics:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - remotetap
        - batch
      exporters:
        - debug # Collector complains if a pipeline has no exporter
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - remotetap
        - batch
      exporters:
        - otlp/jaeger
    logs:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - remotetap
        - batch
      exporters:
        - debug # Collector complains if a pipeline has no exporter
```

And a `compose.yaml` similar to this:
```yaml
services:
  collector:
    depends_on:
      tails:
        condition: service_healthy
      jaeger:
        condition: service_healthy
    image: docker.io/otel/opentelemetry-collector-contrib:0.98.0@sha256:5cea85bcbc734a3c0a641368e5a4ea9d31b472997e9f2feca57eeb4a147fcf1a
    environment:
      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md#best-practices
      GOMEMLIMIT: "400MiB"
      JAEGER_OTLP_ENDPOINT: "jaeger:4317"
      TAILS_OPAMP_ENDPOINT: "ws://tails:4000/v1/opamp"
    command:
      - "--config=/config/local.yaml"
      - "--feature-gates=+component.UseLocalHostAsDefaultHost"
    expose:
      - "4317"
    # No healthcheck, because there is no binary in the image that we could use.
    volumes:
      - "./opentelemetry-collector-config/:/config/:ro"
    deploy:
      resources:
        limits:
          memory: 512MiB
        reservations:
          memory: 512MiB
  tails:
    image: ghcr.io/jaronoff97/tails:v0.0.7@sha256:a8e1d373c48f33a087efc43089e6ecfd75c037ff4775c7e524cc5e17f6a31f33
    environment:
      SECRET_KEY_BASE: # REDACTED
      REMOTE_TAP_ENDPOINT: "ws://collector:12001"
    ports:
      - published: 4000
        target: 4000
    healthcheck:
      # wget is not available, use bash magic file:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/4000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128MiB
        reservations:
          memory: 128MiB
  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.56.0@sha256:d2cd4c226624bdc116decd3106091b4df9882da8db42f8550293596cab79b8ea
    command:
      - "--collector.otlp.grpc.tls.enabled=false"
      - "--log-level=warn"
    ports:
      - published: 16686
        target: 16686
    healthcheck:
      test: ["CMD", "wget", "-T1", "http://localhost:16686/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512MiB
        reservations:
          memory: 512MiB
```
